# Generated by Django 4.2.7 on 2025-04-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_clinicas', '0002_move_endodontic_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaoatendimento',
            name='cad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CAD (Localizador Apical Eletrônico)'),
        ),
        migrations.AlterField(
            model_name='sessaoatendimento',
            name='ctp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CTP (Comprimento de Trabalho Provisório)'),
        ),
        migrations.AlterField(
            model_name='sessaoatendimento',
            name='im',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='IM (Instrumento de Memória)'),
        ),
        migrations.AlterField(
            model_name='sessaoatendimento',
            name='lai',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='LAI (Limite Apical de Instrumentação)'),
        ),
        migrations.AlterField(
            model_name='sessaoatendimento',
            name='medicacao_sistemica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medicação Sistêmica'),
        ),
        migrations.AlterField(
            model_name='sessaoatendimento',
            name='solucao_irrigadora',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Solução irrigadora'),
        ),
    ]
