# Generated by Django 4.2.7 on 2025-04-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_clinicas', '0003_alter_sessaoatendimento_cad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamento_medico', models.BooleanField(default=False, verbose_name='Está sob tratamento médico?')),
                ('uso_medicamentos', models.TextField(blank=True, null=True, verbose_name='Uso de medicamentos')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('problemas_cardiacos', models.BooleanField(default=False, verbose_name='Problemas Cardíacos')),
                ('gastrite_ulceras', models.BooleanField(default=False, verbose_name='Gastrite/Úlceras')),
                ('problemas_neurologicos', models.BooleanField(default=False, verbose_name='Problemas Neurológicos')),
                ('problemas_coagulacao', models.BooleanField(default=False, verbose_name='Problemas de Coagulação')),
                ('diabetes', models.BooleanField(default=False, verbose_name='Diabetes')),
                ('sensibilidade_anestesicos', models.BooleanField(default=False, verbose_name='Sensibilidade a anestésicos/antibióticos')),
                ('pressao_arterial', models.BooleanField(default=False, verbose_name='Pressão arterial alterada')),
                ('gravidez', models.BooleanField(default=False, verbose_name='Gravidez')),
                ('sifilis', models.BooleanField(default=False, verbose_name='Sífilis')),
                ('epilepsia', models.BooleanField(default=False, verbose_name='Epilepsia')),
                ('lesao_figado', models.BooleanField(default=False, verbose_name='Lesão de Fígado')),
                ('lesao_renal', models.BooleanField(default=False, verbose_name='Lesão Renal')),
                ('outras_condicoes', models.TextField(blank=True, null=True, verbose_name='Outras condições')),
                ('historia_dental', models.TextField(blank=True, null=True, verbose_name='História Dental')),
                ('dor_presente', models.BooleanField(default=False, verbose_name='Dor Presente')),
                ('estimulo', models.CharField(blank=True, choices=[('E', 'Espontânea'), ('T', 'Térmico'), ('Q', 'Químico'), ('M', 'Mecânico')], max_length=1, null=True, verbose_name='Estímulo')),
                ('localizacao', models.CharField(blank=True, choices=[('L', 'Localizada'), ('D', 'Difusa'), ('R', 'Referida')], max_length=1, null=True, verbose_name='Localização')),
                ('frequencia', models.CharField(blank=True, choices=[('C', 'Constante'), ('I', 'Intermitente')], max_length=1, null=True, verbose_name='Frequência')),
                ('intensidade', models.CharField(blank=True, choices=[('L', 'Leve'), ('M', 'Moderada'), ('I', 'Intensa')], max_length=1, null=True, verbose_name='Intensidade')),
                ('inicio', models.CharField(blank=True, choices=[('R', 'Recentemente'), ('A', 'Antigo')], max_length=1, null=True, verbose_name='Início')),
                ('duracao', models.CharField(blank=True, choices=[('S', 'Segundos'), ('M', 'Minutos'), ('H', 'Horas'), ('D', 'Dias')], max_length=1, null=True, verbose_name='Duração')),
                ('exacerbada_frio', models.BooleanField(default=False, verbose_name='Exacerbada por Frio')),
                ('exacerbada_quente', models.BooleanField(default=False, verbose_name='Exacerbada por Quente')),
                ('exacerbada_doce', models.BooleanField(default=False, verbose_name='Exacerbada por Doce')),
                ('exacerbada_mastigacao', models.BooleanField(default=False, verbose_name='Exacerbada por Mastigação')),
                ('exacerbada_outro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Exacerbada por Outro')),
                ('aliviada_ar', models.BooleanField(default=False, verbose_name='Aliviada por Ar')),
                ('aliviada_analgesico', models.BooleanField(default=False, verbose_name='Aliviada por Analgésico')),
                ('aliviada_decubito', models.BooleanField(default=False, verbose_name='Aliviada por Decúbito')),
                ('aliviada_outro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aliviada por Outro')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico clínico radiográfico provável')),
                ('tratamento_indicado', models.CharField(blank=True, choices=[('P', 'Pulpectomia'), ('N', 'Necropulpectomia'), ('R', 'Retratamento'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Tratamento indicado')),
                ('acidentes_operatorios', models.TextField(blank=True, null=True, verbose_name='Acidentes Operatórios')),
                ('pos_tratamento', models.TextField(blank=True, null=True, verbose_name='Pós Tratamento')),
                ('preservacao', models.CharField(blank=True, choices=[('1', '1 mês'), ('3', '3 meses'), ('6', '6 meses'), ('12', '12 meses'), ('24', '24 meses')], max_length=2, null=True, verbose_name='Preservação')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='Data término do tratamento')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
            },
        ),
        migrations.CreateModel(
            name='ExameClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assimetria_facial', models.BooleanField(default=False, verbose_name='Assimetria facial')),
                ('tumefacao', models.BooleanField(default=False, verbose_name='Tumefação')),
                ('fistula_cutanea', models.BooleanField(default=False, verbose_name='Fístula cutânea')),
                ('enfartamento_ganglionar', models.BooleanField(default=False, verbose_name='Enfartamento Ganglionar')),
                ('fistula', models.BooleanField(default=False, verbose_name='Fístula')),
                ('ulceracao', models.BooleanField(default=False, verbose_name='Ulceração')),
                ('alteracao_cor', models.BooleanField(default=False, verbose_name='Alteração de cor')),
                ('tumefacao_apical', models.BooleanField(default=False, verbose_name='Tumefação apical')),
                ('bolsa_periodontal', models.BooleanField(default=False, verbose_name='Bolsa Periodontal')),
                ('carie', models.BooleanField(default=False, verbose_name='Cárie')),
                ('restauracao', models.CharField(choices=[('N', 'Não possui'), ('M', 'Metálica'), ('R', 'Resina'), ('O', 'Outro')], default='N', max_length=1, verbose_name='Restauração')),
                ('exposicao_pulpar', models.CharField(choices=[('N', 'Não possui'), ('P', 'Patológica'), ('M', 'Mecânica')], default='N', max_length=1, verbose_name='Exposição pulpar')),
                ('alteracao_cor_coroa', models.BooleanField(default=False, verbose_name='Alteração de cor da coroa')),
                ('mobilidade', models.BooleanField(default=False, verbose_name='Mobilidade')),
                ('teste_frio', models.CharField(blank=True, choices=[('N', 'Normal'), ('A', 'Ausente'), ('D', 'Diminuída'), ('E', 'Exacerbada')], max_length=1, null=True, verbose_name='Teste Frio')),
                ('teste_quente', models.CharField(blank=True, choices=[('N', 'Normal'), ('A', 'Ausente'), ('D', 'Diminuída'), ('E', 'Exacerbada')], max_length=1, null=True, verbose_name='Teste Quente')),
                ('percussao_vertical', models.CharField(blank=True, choices=[('N', 'Negativa'), ('P', 'Positiva')], max_length=1, null=True, verbose_name='Percussão Vertical')),
                ('percussao_horizontal', models.CharField(blank=True, choices=[('N', 'Negativa'), ('P', 'Positiva')], max_length=1, null=True, verbose_name='Percussão Horizontal')),
                ('palpacao_apical', models.CharField(blank=True, choices=[('N', 'Negativa'), ('P', 'Positiva')], max_length=1, null=True, verbose_name='Palpação Apico-Cervical')),
                ('camara_pulpar', models.CharField(blank=True, choices=[('N', 'Normal'), ('C', 'Calcificada'), ('A', 'Alterada')], max_length=1, null=True, verbose_name='Câmara Pulpar')),
                ('canal_radicular', models.CharField(blank=True, choices=[('N', 'Normal'), ('A', 'Atresiados'), ('C', 'Calcificados'), ('D', 'Dilacerados')], max_length=1, null=True, verbose_name='Canal Radicular')),
                ('pericemento', models.CharField(blank=True, choices=[('N', 'Normal'), ('E', 'Espessado')], max_length=1, null=True, verbose_name='Pericemento')),
                ('rarefacao_ossea', models.BooleanField(default=False, verbose_name='Rarefação óssea')),
                ('rarefacao_tipo', models.CharField(blank=True, choices=[('D', 'Difusa'), ('C', 'Circunscrita')], max_length=1, null=True, verbose_name='Tipo de Rarefação')),
                ('nodulos', models.BooleanField(default=False, verbose_name='Nódulos')),
                ('deformacao_assoalho', models.BooleanField(default=False, verbose_name='Deformação do assoalho')),
                ('trepanacao', models.BooleanField(default=False, verbose_name='Trepanação')),
                ('reabsorcao_interna', models.BooleanField(default=False, verbose_name='Reabsorção interna')),
                ('reabsorcao_externa', models.BooleanField(default=False, verbose_name='Reabsorção externa')),
                ('instrumento_fraturado', models.BooleanField(default=False, verbose_name='Instrumento fraturado')),
                ('degrau_apical', models.BooleanField(default=False, verbose_name='Degrau apical')),
                ('fratura_radicular', models.BooleanField(default=False, verbose_name='Fratura radicular')),
                ('dilaceracao_apical', models.BooleanField(default=False, verbose_name='Dilaceração apical')),
                ('rizogenese_incompleta', models.BooleanField(default=False, verbose_name='Rizogênese incompleta')),
                ('osteite_condensante', models.BooleanField(default=False, verbose_name='Osteíte Condensante')),
                ('hipercementose', models.BooleanField(default=False, verbose_name='Hipercementose')),
            ],
            options={
                'verbose_name': 'Exame Clínico',
                'verbose_name_plural': 'Exames Clínicos',
            },
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='acidentes_operatorios',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='aliviada_analgesico',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='aliviada_ar',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='aliviada_decubito',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='aliviada_outro',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='alteracao_cor',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='alteracao_cor_coroa',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='assimetria_facial',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='bolsa_periodontal',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='camara_pulpar',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='canal_radicular',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='carie',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='data_termino',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='deformacao_assoalho',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='degrau_apical',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='dilaceracao_apical',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='dor_presente',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='duracao',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='enfartamento_ganglionar',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='epilepsia',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='estimulo',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='exacerbada_doce',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='exacerbada_frio',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='exacerbada_mastigacao',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='exacerbada_outro',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='exacerbada_quente',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='exposicao_pulpar',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='fistula',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='fistula_cutanea',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='fratura_radicular',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='frequencia',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='gastrite_ulceras',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='gravidez',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='hipercementose',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='historia_dental',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='instrumento_fraturado',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='intensidade',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='lesao_figado',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='lesao_renal',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='mobilidade',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='nodulos',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='osteite_condensante',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='outras_condicoes',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='palpacao_apical',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='percussao_horizontal',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='percussao_vertical',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='pericemento',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='pos_tratamento',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='preservacao',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='pressao_arterial',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='problemas_cardiacos',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='problemas_coagulacao',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='problemas_neurologicos',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='rarefacao_ossea',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='rarefacao_tipo',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='reabsorcao_externa',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='reabsorcao_interna',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='restauracao',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='rizogenese_incompleta',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='sensibilidade_anestesicos',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='sifilis',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='teste_frio',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='teste_quente',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='tratamento_indicado',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='tratamento_medico',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='trepanacao',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='tumefacao',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='tumefacao_apical',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='ulceracao',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='uso_medicamentos',
        ),
        migrations.RemoveField(
            model_name='sessaoatendimento',
            name='data_registro',
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='anamnese',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='fichas_clinicas.anamnese'),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='exame_clinico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='fichas_clinicas.exameclinico'),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='diagnostico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='fichas_clinicas.diagnostico'),
        ),
    ]
