# Generated by Django 4.2.7 on 2025-04-11 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_clinicas', '0005_fix_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoatendimento',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de registro'),
            preserve_default=False,
        ),
    ]
