# Generated by Django 4.2.7 on 2025-04-11 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_clinicas', '0006_sessaoatendimento_data_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaclinica',
            name='data_abertura',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de abertura'),
        ),
    ]
