# Generated by Django 4.2.7 on 2025-04-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_clinicas', '0007_alter_fichaclinica_data_abertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoatendimento',
            name='hora_sessao',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário da sessão'),
        ),
        migrations.AddField(
            model_name='sessaoatendimento',
            name='tipo_sessao',
            field=models.CharField(blank=True, choices=[('Inicial', 'Consulta Inicial'), ('Retorno', 'Retorno'), ('Tratamento', 'Tratamento'), ('Finalização', 'Finalização')], max_length=20, null=True, verbose_name='Tipo de sessão'),
        ),
    ]
